# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2
jobs:
  build:
    docker:
      # specify the version
      - image: circleci/golang:1.8

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/postgres:9.4

    #### TEMPLATE_NOTE: go expects specific checkout path representing url
    #### expecting it in the form of
    ####   /go/src/github.com/circleci/go-tool
    ####   /go/src/bitbucket.org/circleci/go-tool
    working_directory: /go/src/github.com/Golang-Coach/Scheduler
    steps:
      - checkout

      - run: |
                go get github.com/kardianos/govendor
                go get github.com/smartystreets/goconvey
                go get github.com/mitchellh/gox
                go get golang.org/x/tools/cmd/cover
                go get github.com/axw/gocov/gocov
                go get github.com/mattn/goveralls
                go get github.com/stretchr/testify
                go get github.com/onsi/ginkgo/ginkgo
                go get github.com/modocache/gover

      - run: govendor sync

      - run: ginkgo -r  -cover -trace -race
      - run: gover
      - run: goveralls -coverprofile=gover.coverprofile -service=circle-ci -repotoken $COVERALL_TOKEN

      - run: GOOS=linux go build -o main main.go
      - run: zip main.zip main

      - store_artifacts:
          path: main.zip

      - setup_remote_docker

      - run: |
                TAG=0.1.$CIRCLE_BUILD_NUM
                docker login -u $DOCKER_USER -p $DOCKER_PASS         # (5)
                docker build -t   golangcoach/scheduler:$TAG .      # (4)
                docker push golangcoach/scheduler:$TAG
                docker build -t   golangcoach/scheduler .      # (4)
                docker push golangcoach/scheduler
