// Code generated by mockery v1.0.0
package mocks

import mgo "gopkg.in/mgo.v2"
import mock "github.com/stretchr/testify/mock"
import models "github.com/Golang-Coach/Scheduler/models"

// IDataStore is an autogenerated mock type for the IDataStore type
type IDataStore struct {
	mock.Mock
}

// AddPackage provides a mock function with given fields: pack
func (_m *IDataStore) AddPackage(pack models.RepositoryInfo) error {
	ret := _m.Called(pack)

	var r0 error
	if rf, ok := ret.Get(0).(func(models.RepositoryInfo) error); ok {
		r0 = rf(pack)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// FindPackage provides a mock function with given fields: query
func (_m *IDataStore) FindPackage(query interface{}) *mgo.Query {
	ret := _m.Called(query)

	var r0 *mgo.Query
	if rf, ok := ret.Get(0).(func(interface{}) *mgo.Query); ok {
		r0 = rf(query)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*mgo.Query)
		}
	}

	return r0
}

// FindPackageWithinLimit provides a mock function with given fields: query, skip, limit
func (_m *IDataStore) FindPackageWithinLimit(query interface{}, skip int, limit int) *mgo.Query {
	ret := _m.Called(query, skip, limit)

	var r0 *mgo.Query
	if rf, ok := ret.Get(0).(func(interface{}, int, int) *mgo.Query); ok {
		r0 = rf(query, skip, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*mgo.Query)
		}
	}

	return r0
}

// UpdatePackage provides a mock function with given fields: pack
func (_m *IDataStore) UpdatePackage(pack *models.RepositoryInfo) error {
	ret := _m.Called(pack)

	var r0 error
	if rf, ok := ret.Get(0).(func(*models.RepositoryInfo) error); ok {
		r0 = rf(pack)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
