// Code generated by mockery v1.0.0
package mocks

import interfaces "github.com/Golang-Coach/Scheduler/interfaces"
import mock "github.com/stretchr/testify/mock"

// IDataStore is an autogenerated mock type for the IDataStore type
type IDataStore struct {
	mock.Mock
}

// GetCollection provides a mock function with given fields:
func (_m *IDataStore) GetCollection() interfaces.ICollection {
	ret := _m.Called()

	var r0 interfaces.ICollection
	if rf, ok := ret.Get(0).(func() interfaces.ICollection); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(interfaces.ICollection)
		}
	}

	return r0
}
